export const STACK_USERS = 'STACK_USERS';

export const FETCH_USERS = 'FETCH_USERS';

export const FILTER_BY_NAME = 'FILTER_BY_NAME';

export const FILTER_BY_NATIONALITY = 'FILTER_BY_NATIONALITY';

export const LOADING = 'LOADING';

export const INFINITE_SCROLL = 'INFINITE_SCROLL';
